version: '3'

services:
  poll:
    build:
      context: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    restart: on-failure

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - redis-tier

  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    networks:
      - back-tier
    restart: on-failure

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    networks:
      - result-tier
      - back-tier

  result:
    build:
      context: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    networks:
      - result-tier
    restart: on-failure

networks:
  poll-tier:
  result-tier:
  back-tier:
  redis-tier:

volumes:
  db-data: